#screen dimensions

TILE_SIZE = 64
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

#game play

#speeds are in ixels per frame and frame rate is 1/60 seconds
PLAYER_SPEED = 3
FISH_SPEED_MIN = 0.5
FISH_SPEED_MAX = 3

ENEMY_SPEED_MIN = 2
ENEMY_SPEED_MAX = 5

NUM_LIVES = 3

BULLET_SPEED = 10
BULLET_WIDTH = 15
BULLET_HEIGHT = 3
BULLET_COLOR = (215, 53, 2)